#!/usr/bin/env python3
"""
Agent Linker - Manage projections for multi-tool agent discovery

Creates/queries/removes symlinks or generated files from a canonical agent
source directory to the agent directories of supported development tools.

Usage:
    link_agent.py <agent-path>                        # Project to default user-level targets
    link_agent.py <agent-path> --project-root <path> # Project into project tool dirs
    link_agent.py <agent-path> --targets claude,codex
    link_agent.py <agent-path> --status
    link_agent.py <agent-path> --unlink
    link_agent.py <agent-path> --force
"""

import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from utils import parse_markdown_frontmatter


LINK_TARGETS = {
    "claude": ".claude/agents",
    "codex": ".codex/agents",
}

USER_DEFAULT_TARGETS = ["claude", "codex"]
PROJECT_DEFAULT_TARGETS = ["claude", "codex"]
GENERATED_HEADER = "# Generated by"


def resolve_agent_path(raw_path):
    """Resolve and validate the canonical agent source path."""
    agent_path = Path(raw_path).expanduser().resolve()
    if not agent_path.is_dir():
        print(f"❌ Error: Not a directory: {agent_path}")
        return None
    agent_md = agent_path / "AGENT.md"
    if not agent_md.exists():
        print(f"❌ Error: No AGENT.md found in {agent_path}")
        return None
    return agent_path


def parse_agent(agent_path: Path) -> tuple[str, str, str]:
    """Return (name, description, body) from the canonical AGENT.md."""
    metadata, body = parse_markdown_frontmatter(agent_path / "AGENT.md")
    name = metadata.get("name") or agent_path.name
    description = metadata.get("description", "")
    if not description:
        raise ValueError(f"AGENT.md at {agent_path} is missing a description field")
    return name, description, body


def get_target_dir(tool_name, project_root=None):
    """Return the absolute target directory for a tool."""
    rel = LINK_TARGETS.get(tool_name)
    if rel is None:
        return None
    base = Path(project_root).expanduser().resolve() if project_root else Path.home()
    return base / rel


def compute_relative_symlink(link_location, target_real_path):
    """Compute a relative symlink value."""
    return os.path.relpath(target_real_path, link_location.parent)


def render_codex_agent(name: str, description: str, body: str) -> str:
    """Render a Codex custom agent TOML file."""
    return (
        "# Generated by `scripts/link_agent.py`.\n"
        "# Edit the canonical AGENT.md instead.\n\n"
        f"name = {json.dumps(name)}\n"
        f"description = {json.dumps(description)}\n"
        f"developer_instructions = {json.dumps(body.rstrip())}\n"
    )


def ensure_symlink(link_path: Path, target_path: Path, force: bool) -> str:
    """Ensure the target path is a symlink to the canonical AGENT.md."""
    link_path.parent.mkdir(parents=True, exist_ok=True)
    rel_target = compute_relative_symlink(link_path, target_path)

    if link_path.is_symlink():
        existing = os.readlink(link_path)
        existing_resolved = (link_path.parent / existing).resolve()
        if existing_resolved == target_path.resolve():
            return "unchanged"
        if not force:
            raise RuntimeError(f"{link_path} points to {existing}; use --force to overwrite")
        link_path.unlink()
    elif link_path.exists():
        if not force:
            raise RuntimeError(f"{link_path} exists as a real file; use --force to overwrite")
        link_path.unlink()

    link_path.symlink_to(rel_target)
    return "created"


def ensure_codex_file(link_path: Path, content: str, force: bool) -> str:
    """Ensure the Codex projection exists and is current."""
    link_path.parent.mkdir(parents=True, exist_ok=True)

    if link_path.exists():
        current = link_path.read_text()
        if current == content:
            return "unchanged"
        if GENERATED_HEADER not in current and not force:
            raise RuntimeError(f"{link_path} exists and is not a generated file; use --force to overwrite")

    link_path.write_text(content)
    return "updated"


def link_agent(agent_path, targets=None, force=False, project_root=None):
    """Create projections for the agent in the selected tool directories."""
    if targets is None:
        targets = PROJECT_DEFAULT_TARGETS if project_root else USER_DEFAULT_TARGETS

    name, description, body = parse_agent(agent_path)
    created, updated, skipped, warnings = 0, 0, 0, 0

    for tool in targets:
        target_dir = get_target_dir(tool, project_root=project_root)
        if target_dir is None:
            print(f"  ⚠  Unknown tool: {tool}")
            warnings += 1
            continue

        try:
            if tool == "claude":
                status = ensure_symlink(target_dir / f"{name}.md", agent_path / "AGENT.md", force)
            else:
                status = ensure_codex_file(target_dir / f"{name}.toml", render_codex_agent(name, description, body), force)
        except RuntimeError as exc:
            print(f"  ⚠  {tool}: {exc}")
            warnings += 1
            continue

        if status == "created":
            print(f"  ✅ {tool}: created projection for {name}")
            created += 1
        elif status == "updated":
            print(f"  ✅ {tool}: updated projection for {name}")
            updated += 1
        else:
            print(f"  ✓  {tool}: already current")
            skipped += 1

    return created, updated, skipped, warnings


def unlink_agent(agent_path, targets=None, project_root=None):
    """Remove projections for the agent from the selected tool directories."""
    if targets is None:
        targets = PROJECT_DEFAULT_TARGETS if project_root else USER_DEFAULT_TARGETS

    name, _, _ = parse_agent(agent_path)
    removed, not_found, warnings = 0, 0, 0

    for tool in targets:
        target_dir = get_target_dir(tool, project_root=project_root)
        if target_dir is None:
            continue

        projection = target_dir / (f"{name}.md" if tool == "claude" else f"{name}.toml")
        if not projection.exists() and not projection.is_symlink():
            print(f"  -  {tool}: no projection found")
            not_found += 1
            continue

        if tool == "claude" and projection.is_symlink():
            projection.unlink()
            print(f"  🗑  {tool}: removed {projection}")
            removed += 1
            continue

        if tool == "codex":
            current = projection.read_text()
            if GENERATED_HEADER in current:
                projection.unlink()
                print(f"  🗑  {tool}: removed {projection}")
                removed += 1
            else:
                print(f"  ⚠  {tool}: {projection} is not a generated file")
                warnings += 1
            continue

        print(f"  ⚠  {tool}: {projection} is not removable as a managed projection")
        warnings += 1

    return removed, not_found, warnings


def status_agent(agent_path, targets=None, project_root=None):
    """Display the projection status of an agent across selected tools."""
    if targets is None:
        targets = PROJECT_DEFAULT_TARGETS if project_root else USER_DEFAULT_TARGETS

    name, _, _ = parse_agent(agent_path)
    scope_label = (
        f"project {Path(project_root).expanduser().resolve()}"
        if project_root is not None
        else "user"
    )
    print(f"\n📋 Projection status for: {name}")
    print(f"   Source: {agent_path}")
    print(f"   Scope: {scope_label}\n")

    for tool in targets:
        target_dir = get_target_dir(tool, project_root=project_root)
        if target_dir is None:
            continue

        projection = target_dir / (f"{name}.md" if tool == "claude" else f"{name}.toml")
        if tool == "claude":
            if projection.is_symlink():
                dest = os.readlink(projection)
                print(f"  ✅ {tool:8s} → {dest}")
            elif projection.exists():
                print(f"  📄 {tool:8s}   real file (not a symlink)")
            else:
                print(f"  ❌ {tool:8s}   not projected")
        else:
            if projection.exists():
                current = projection.read_text()
                suffix = "generated" if GENERATED_HEADER in current else "manual"
                print(f"  ✅ {tool:8s}   {projection.name} ({suffix})")
            else:
                print(f"  ❌ {tool:8s}   not projected")


def parse_targets(targets_str):
    """Parse comma-separated target list."""
    targets = [t.strip().lower() for t in targets_str.split(",") if t.strip()]
    valid = []
    for target in targets:
        if target in LINK_TARGETS:
            valid.append(target)
        else:
            print(f"⚠  Unknown target '{target}'. Available: {', '.join(LINK_TARGETS.keys())}")
    return valid if valid else None


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Manage projections for multi-tool agent discovery",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s ~/.agents/agents/my-agent
  %(prog)s ~/.agents/agents/my-agent --project-root .
  %(prog)s ~/.agents/agents/my-agent --targets claude,codex
  %(prog)s ~/.agents/agents/my-agent --status
  %(prog)s ~/.agents/agents/my-agent --unlink
        """,
    )
    parser.add_argument("agent_path", help="Path to the canonical agent directory")
    parser.add_argument("--targets", help="Comma-separated tool names (default: claude,codex)")
    parser.add_argument(
        "--project-root",
        help="Project root for project-scoped projections (uses <project-root>/.claude/agents and <project-root>/.codex/agents)",
    )
    parser.add_argument("--status", action="store_true", help="Show projection status only")
    parser.add_argument("--unlink", action="store_true", help="Remove projections")
    parser.add_argument("--force", action="store_true", help="Overwrite existing non-matching projections")

    args = parser.parse_args()
    agent_path = resolve_agent_path(args.agent_path)
    if agent_path is None:
        sys.exit(1)

    targets = parse_targets(args.targets) if args.targets else None
    project_root = args.project_root

    if args.status:
        status_agent(agent_path, targets, project_root=project_root)
    elif args.unlink:
        print(f"🗑  Unlinking: {agent_path.name}")
        removed, not_found, warnings = unlink_agent(agent_path, targets, project_root=project_root)
        print(f"\nDone: {removed} removed, {not_found} not found, {warnings} warnings")
    else:
        print(f"🔗 Projecting: {agent_path.name}")
        created, updated, skipped, warnings = link_agent(
            agent_path,
            targets,
            force=args.force,
            project_root=project_root,
        )
        print(
            f"\nDone: {created} created, {updated} updated, {skipped} skipped, {warnings} warnings"
        )

    sys.exit(0)


if __name__ == "__main__":
    main()
